In [3]:
import numpy as np

### `numpy.random.rand(size)`
使用 `rand` 生成指定参数的一个或多个服从 [0, 1) 均匀分布的随机数。<br><br>
参数：
- `size`：输出随机数的形状，默认为 None，即输出一个随机数。

In [4]:
np.random.rand(2,4)

array([[0.7886613 , 0.80619049, 0.1360958 , 0.45210265],
       [0.10561452, 0.969438  , 0.31593565, 0.54889768]])

### `numpy.random.randn(size)`
使用 `randn` 生成指定参数的一个或多个服从标准正态分布（均值为 0，标准差为 1）的随机数。<br><br>
参数：
- `size`：输出随机数的形状，默认为 None，即输出一个随机数。

In [5]:
np.random.randn(2,3)

array([[0.8530352 , 0.17937371, 1.84134749],
       [1.97435205, 0.44837523, 0.40442246]])

### `numpy.random.randint(low, high, size, dtype)`
使用 `randint` 生成指定参数的一个或多个服从 [low, high) 均匀分布的整数随机数。<br><br>
参数：
- `low`：生成随机数的下界（包含）。
- `high=None`：生成随机数的上界（不包含）。如果未指定，则生成的随机数在 [0, low) 范围内。
- `size=None`：输出随机数的形状，默认为 None，即输出一个随机数。
- `dtype=int`：输出随机数的数据类型，默认为 int。

In [7]:
print(np.random.randint(1,10,(3,4)))

[[3 4 6 9]
 [1 4 4 1]
 [4 4 9 1]]
