In [2]:
import numpy as np

### `numpy.random.rand(size)`
使用 `rand` 生成指定参数的一个或多个服从 [0, 1) 均匀分布的随机数。<br><br>
参数：
- `size`：输出随机数的形状，默认为 None，即输出一个随机数。

In [4]:
np.random.rand(2,4)

array([[0.7886613 , 0.80619049, 0.1360958 , 0.45210265],
       [0.10561452, 0.969438  , 0.31593565, 0.54889768]])

### `numpy.random.randn(size)`
使用 `randn` 生成指定参数的一个或多个服从标准正态分布（均值为 0，标准差为 1）的随机数。<br><br>
参数：
- `size`：输出随机数的形状，默认为 None，即输出一个随机数。

In [5]:
np.random.randn(2,3)

array([[0.8530352 , 0.17937371, 1.84134749],
       [1.97435205, 0.44837523, 0.40442246]])

### `numpy.random.randint(low, high, size, dtype)`
使用 `randint` 生成指定参数的一个或多个服从 [low, high) 均匀分布的整数随机数。<br><br>
参数：
- `low`：生成随机数的下界（包含）。
- `high=None`：生成随机数的上界（不包含）。如果未指定，则生成的随机数在 [0, low) 范围内。
- `size=None`：输出随机数的形状，默认为 None，即输出一个随机数。
- `dtype=int`：输出随机数的数据类型，默认为 int。

In [7]:
print(np.random.randint(1,10,(3,4)))

[[3 4 6 9]
 [1 4 4 1]
 [4 4 9 1]]


### `numpy.random.choice(a, size, replace, p)`
从给定的一维数组 `a` 中生成随机样本。

**参数**
- `a` : 1-D array-like or int
    - 如果为数组，则从其元素中随机选择。
    - 如果为整数，则从 `np.arange(a)` 中随机选择。
- `size=None` : int or tuple of ints, _optional_
    - 输出形状。默认为 `None`，返回单个值。
- `replace=True` : bool, _optional_
    - 抽样是否是有放回的。默认为 `True`。
- `p=None` : 1-D array-like, _optional_
    - 与 `a` 中每个条目相关联的概率。默认为均匀分布。

**返回**
- `samples` : single item or ndarray
    - 生成的随机样本。

**示例**


In [12]:
arrNum = np.random.choice(10, (2, 3), False)
fruits = ['香蕉', '橙子', '苹果', '草莓', '葡萄']
arrStr = np.random.choice(fruits, 3, False)

print(arrNum)
print(arrStr)

[[1 5 7]
 [3 6 8]]
['草莓' '苹果' '香蕉']
