### `np.where()` 二元运算

In [7]:
import numpy as np
budgets = np.array([
    [34, 56, 23, 67, 45],
    [29, 61, 42, 38, 55],
    [47, 33, 60, 25, 41],
    [52, 68, 31, 44, 39],
    [58, 27, 50, 63, 36],
    [21, 48, 70, 30, 59],
    [65, 26, 37, 53, 46]
])
isHigh = np.where(budgets >= 60, '高', '低')
print(isHigh)

[['低' '低' '低' '高' '低']
 ['低' '高' '低' '低' '低']
 ['低' '低' '高' '低' '低']
 ['低' '高' '低' '低' '低']
 ['低' '低' '低' '高' '低']
 ['低' '低' '高' '低' '低']
 ['高' '低' '低' '低' '低']]


### `np.sort()` 排序

In [8]:
import numpy as np
nums = np.array([1, 3, 2, 5])
numsSorted = np.sort(nums)
print(numsSorted)

[1 2 3 5]


### `np.ceil()` 向上取整

In [9]:
import numpy as np
nums = np.array([4.3, 5.001, 6.7, 7.0])
numsCail = np.ceil(nums)
print(numsCail)

[5. 6. 7. 7.]


### `np.floor()` 向下取整

In [10]:
import numpy as np
nums = np.array([4.3, 5.001, 6.7, 7.0])
numsFloor = np.floor(nums)
print(numsFloor)

[4. 5. 6. 7.]


In [11]:
# 1. 分别使用
nums = np.array([3.2, 4.8, 5.5, 2.1])
numsFloor = np.floor(nums)
print(numsFloor)
numsCail = np.ceil(nums)
print(numsCail)

[3. 4. 5. 2.]
[4. 5. 6. 3.]


In [12]:
# 2. 租车问题
print(np.ceil(43 / 10))

5.0


In [13]:
# 3. 买书
print(np.floor(100 / 18))

5.0


In [14]:
import numpy as np
# 排序
scores = np.sort(np.array([88, 56, 92, 73, 60]))
# 前三名
print(scores[-3:])

# 数学竞赛
scores2 = np.sort(np.array([75, 98, 82, 65, 91, 88, 70]))
print(np.sort(scores2)[:3])

# 中位数
print( np.sort(np.array([10, 5, 20, 15, 30]))[len(np.sort(np.array([10, 5, 20, 15, 30])))//2])

[73 88 92]
[65 70 75]
15


### `np.loadtext()` 从文件导入文本

用法：
```python
import numpy as np
def loadtxt(
    fname: _FName,
    delimiter: str | None = None,
    converters: Mapping[int | str, (str) -> Any] | ((str) -> Any) | None = None,
    usecols: int | Sequence[int] | None = None,
    skiprows: int = 0,
) -> NDArray[float64]: ...
```

In [19]:
import numpy as np
set = np.loadtxt("/Users/pylorsun/Documents/Study/2025-2026第二学期/PythonAyz/Code/Assets/data.csv", skiprows=1, delimiter=',', usecols=(0, 2))
np.mean(set)

np.float64(85.375)